name: Subir Balones de Oro a Mongo Atlas

on:
  push:
    branches:
      - main 

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install beautifulsoup4  # Solución adicional

      - name: Verificar dependencias instaladas
        run: pip list

      - name: Agregar variables de entorno
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: echo "Variables de entorno configuradas"

      - name: Ejecutar script
        run: python cargarBalonesDeOro.py
