name: Cargar a Mongo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener el código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install requests pymongo python-dotenv

      - name: Ejecutar cargarPremiosOscar.py
        run: |
          python cargarPremiosOscar.py
