name: Ejecutar cargarPremiosOscar

on:
  workflow_dispatch: # Permite ejecutar manualmente la acción

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configurar variables de entorno
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}
      run: echo "Variable MONGO_URI configurada"

    - name: Ejecutar el script
      run: python cargarPremiosOscar.py
