name: Run cargarPremiosOscar.py

on:
  push:
    branches:
      - main  # O cualquier otra rama en la que quieras que se ejecute la acción
  workflow_dispatch:  # Esto permite ejecutar la acción manualmente desde la interfaz de GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pymongo

    - name: Run script
      run: |
        python cargarPremiosOscar.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}  # Usamos el secreto de GitHub

