name: Deploy FastAPI API and Load Data to MongoDB

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t your-dockerhub-username/fastapi-api .

    - name: Push Docker image to Docker Hub
      run: |
        docker push your-dockerhub-username/fastapi-api

    - name: Run FastAPI container
      run: |
        docker run -d -e MONGO_URI=${{ secrets.MONGO_URI }} -p 8000:8000 your-dockerhub-username/fastapi-api

    - name: Load Data into MongoDB
      run: |
        python cargarPremiosOscar.py
      env:
        MONGO_URI: ${{ secrets.MONGO_URI }}

    - name: Clean up Docker containers
      run: |
        docker stop $(docker ps -q)
